language: php

php:
    - 5.4
    - 5.5

before_script:
    ## Composer
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
    - php composer.phar selfupdate
    ## PHP_CodeSniffer
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash
    ## PHP Copy/Paste Detector
    - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar
    ## PHP Mess Detector
    - pear config-set preferred_state beta
    - printf "\n" | pecl install imagick
    - pear channel-discover pear.phpmd.org
    - pear channel-discover pear.pdepend.org
    - pear install --alldeps phpmd/PHP_PMD
    - phpenv rehash

script:
    ## PHP_CodeSniffer
    - phpcs --standard=PSR2 src/
    ## PHP Copy/Paste Detector
    - php phpcpd.phar --verbose src/
    ## PHP Mess Detector
    - phpmd src/ text codesize,unusedcode,naming,design
    ## PHPUnit
    - phpunit
