language: php

php:
    ## - 5.4
    - 5.5

before_script:
    ## Composer
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
    - php composer.phar selfupdate
    ## Pear
    - pear config-set preferred_state beta
    - pear update
    - pear upgrade-all
    - pear install --alldeps PHP_CodeSniffer
    - phpenv rehash

script:
    ## PHP_CodeSniffer
    - phpcs --standard=PSR2 src/
    ## PHPUnit
    - phpunit
